apiVersion: apps/v1
kind: Deployment
metadata:
  name: leadgenius-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leadgenius-ai
  template:
    metadata:
      labels:
        app: leadgenius-ai
    spec:
      containers:
      - name: leadgenius-ai
        image: leadgenius-ai:latest
        ports:
        - containerPort: 5000
resources:
  requests:
    memory: "2Gi"
    cpu: "1"
  limits:
    memory: "4Gi"
    cpu: "2"
