apiVersion: v1
kind: Service
metadata:
  name: leadgenius-ai-service
spec:
  selector:
    app: leadgenius-ai
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
